version: "3"

services:
  api_app:
    container_name: api-app
    depends_on:
      - db
    build:
      context: app
      dockerfile: Dockerfile
    command:
      - "/start"
    env_file:
      - ./.envs/local/.db
      - ./.envs/local/.django
    ports:
      - "8000:8000"

  db:
    container_name: api-db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .envs/local/.db
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
